### ISSUE TITLE
Redirects don't register as wins

### ISSUE THREAD

**Issue by mbjackson7** [B0und/WikiSpeedrun#16]
Some blue links where a different name is used for an article but redirect to the ending articles do not properly register as a win since wins are checked by article title in history rather than article ID.

**Comment by B0und** [comment]
Can you provide an example so i can reproduce this for further testing?
This could probably be fixed by adding another win condition check based on article id, after it loads.

**Comment by mbjackson7** [comment]
I had the ending article of _Proxy server_. I was on the page _Web server_ and used the link _Web proxy_ in the "See also" section, redirects to _Proxy server_, but didn't trigger a win (however it did stop the timer because I had not yet modified the timer to rely on `useIsWin`)
