### ISSUE TITLE
"Sharing settings" doesn't work

### ISSUE THREAD

**Issue by RefractivePrism** [B0und/WikiSpeedrun#20]
When getting a share setting link, the link takes you to the page, and has the data for the Wikipedia pages, put doesn't then actually enter them into the settings. This doesn't work on firefox, edge and chrome.
![image](https://github.com/B0und/WikiSpeedrun/assets/91499539/4c25409b-f6dd-4fa2-8a42-ada49214bf36)

**Comment by B0und** [comment]
Which browser versions are you using?
It works for me using
Chrome Version 120.0.6099.216
Firefox 121

Can you still reproduce the error in private mode? Could be some extensions interfering

**Comment by B0und** [comment]
cant reproduce

**Comment by B0und** [comment]
0x98F0d68C0a69B869260e7CB78341FeAF3d03fb0c
