### ISSUE TITLE
Allow cheating on runs

### ISSUE THREAD

**Issue by VictorWesterlund** [B0und/WikiSpeedrun#24]
Hello!

I found this project from a (not directly) related video posted on Hacker news and thought it was really neat and funny, great job!

----

I noticed that this game blocks "cheating" by disabling Ctrl+F. I wish there was an option to disable this for Wikiplebs like me who has yet to learn how to sniff out the correct sections and such.

This block can be circumvented anyways by opening "find in page" from the menu on most browsers so the block feels kind of arbitrary anyways IMO.

I don't write React so I thought I'd just drop this here as a suggestion.

**Comment by Kawsiphek** [comment]
I agree i would like the option to toggle the ability to use ctrl+f when playing. I have played other wiki games which allow ctrl+f, and considering that using ctrl+f is actually how most people would use wikipedia effectively, i do not consider that to be "cheating." I would like to play with ctrl+f turned on, to get an idea of who out of my group of friends is more effective at searching wikipedia, not who is more effective at scanning articles with your eyes for the link you already expect to be on that page.

**Comment by B0und** [comment]
added a setting
