### ISSUE TITLE
Timer display starts at 30:00 instead of 00:00

### ISSUE THREAD

**Issue by 1NDT** [B0und/WikiSpeedrun#3]
Has no real impact on the game, since time limits seem to be calculated relative to the starting time (for example, setting the time limit to 00:01:00 will end the game when the timer displays 31:00.000). Tried looking at the code to figure out the cause, realized i know nothing about code. Screenshot (hopefully) attached:
![Wikispeedrun timer screenshot](https://user-images.githubusercontent.com/55990211/170869722-34c73bb3-2ea1-44a5-bde3-203e28334605.png)

**Comment by B0und** [comment]
> Has no real impact on the game, since time limits seem to be calculated relative to the starting time (for example, setting the time limit to 00:01:00 will end the game when the timer displays 31:00.000). Tried looking at the code to figure out the cause, realized i know nothing about code. Screenshot (hopefully) attached: ![Wikispeedrun timer screenshot](https://user-images.githubusercontent.com/55990211/170869722-34c73bb3-2ea1-44a5-bde3-203e28334605.png)

What browser are you using, and what version? Does it persist if you refresh the page? I cannot reproduce it on firefox/chrome

**Comment by 1NDT** [comment]
I'm using Opera version 87.0.4390.36 . The issue does persist on refreshing the page, on restarting the browser, as well as restarting the computer. However, the issue also occurs on Firefox version 100.0.2 (image attached). Could it be an operating system thing? I'm on Ubuntu 22.04 LTS, if that helps.
![Wikispeedrun on Firefox](https://user-images.githubusercontent.com/55990211/170877871-e0d257e6-050f-470a-8a43-b87c086e141d.png)

**Comment by B0und** [comment]
> I'm using Opera version 87.0.4390.36 . The issue does persist on refreshing the page, on restarting the browser, as well as restarting the computer. However, the issue also occurs on Firefox version 100.0.2 (image attached). Could it be an operating system thing? I'm on Ubuntu 22.04 LTS, if that helps. ![Wikispeedrun on Firefox](https://user-images.githubusercontent.com/55990211/170877871-e0d257e6-050f-470a-8a43-b87c086e141d.png)

Its some bullshit with Javascript dates. Im looking into it

**Comment by B0und** [comment]
> I'm using Opera version 87.0.4390.36 . The issue does persist on refreshing the page, on restarting the browser, as well as restarting the computer. However, the issue also occurs on Firefox version 100.0.2 (image attached). Could it be an operating system thing? I'm on Ubuntu 22.04 LTS, if that helps. ![Wikispeedrun on Firefox](https://user-images.githubusercontent.com/55990211/170877871-e0d257e6-050f-470a-8a43-b87c086e141d.png)

I have submitted a fix. Please test if it works for you

**Comment by 1NDT** [comment]
Yep, everything seems to be working now, thanks.
