### ISSUE TITLE
make some kind of shareable text on success

### ISSUE THREAD

**Issue by capalmer1013** [B0und/WikiSpeedrun#5]
I just played this and wanted to share my score with a friend and the best I could do was screenshot it.

I think it would be cool to have a copy to clipboard button (like wordle and all those other games) when the game is finished.

I also think it would be cool to either show all of the article leaps or give a link with query parameters to a game with the same text as the share settings but not showing the specific articles that were used.

i.e.
wikispeedrun Bob Caruthers -> Houses of the Holy (10 clicks) 02:27.103
https://wikispeedrun.org/settings?startTitle=Bob+Caruthers&startId=2638372&endTitle=Houses+of+the+Holy&endId=50243 (it would also be nice for this to be shortened)
(optionally, probably if shared without the link)
article1
article 2
article 3
...

**Comment by B0und** [comment]
Now you can share the whole game with a link. No URL shortening yet, but this should be good enough for now
